# Configuraci贸n de las plantillas de issues
blank_issues_enabled: false
contact_links:
  - name:  Discusiones
    url: https://github.com/orgs/thecandylab/discussions
    about: Para preguntas generales y discusiones
  - name:  Consultar documentaci贸n
    url: https://github.com/thecandylab/.github
    about: Revisa la documentaci贸n antes de crear un issue
  - name:  驴Necesitas ayuda con tu PR?
    url: https://github.com/thecandylab/.github/blob/main/README.md
    about: Revisa nuestra gu铆a de contribuci贸n
