# ConfiguraciÃ³n de las plantillas de issues
blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Discusiones
    url: https://github.com/orgs/thecandylab/discussions
    about: Para preguntas generales y discusiones
  - name: ğŸ“š DocumentaciÃ³n
    url: https://thecandylab.com
    about: Consulta nuestra documentaciÃ³n
  - name: ğŸ”’ Reporte de Seguridad
    url: https://github.com/thecandylab/.github/security/policy
    about: Para reportar vulnerabilidades de seguridad de forma privada
