# ConfiguraciÃ³n de las plantillas de issues
blank_issues_enabled: false
contact_links:
  - name: ğŸ›¡ï¸ Reporte de Seguridad
    url: https://github.com/thecandylab/security/advisories/new
    about: Reportar vulnerabilidades de forma segura y privada
  - name: ğŸ’¬ Discusiones
    url: https://github.com/orgs/thecandylab/discussions
    about: Para preguntas generales y discusiones
  - name: ğŸ“š Consultar documentaciÃ³n
    url: https://github.com/thecandylab/.github
    about: Revisa la documentaciÃ³n antes de crear un issue
  - name: ğŸ¤” Â¿Necesitas ayuda con tu PR?
    url: https://github.com/thecandylab/.github/blob/main/README.md
    about: Revisa nuestra guÃ­a de contribuciÃ³n
